name: Lint
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    - name: Install modules
      run: npm install