
name: Bumping version
on:
  push:
    branches:
    - master
jobs:
  bump:
    name: Bumping version
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: Audibene-GMBH/ta.bump-version-action
          ref: master
          token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
          path: push.yml
      - name: Run My Action
        uses: Audibene-GMBH/ta.bump-version-action@master